import React, { useState } from 'react';
import { generateNewsInsights } from '../services/geminiService';
import { Article } from '../types';

interface AIInsightsProps {
  articles: Article[];
}

export const AIInsights: React.FC<AIInsightsProps> = ({ articles }) => {
  const [summary, setSummary] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    const result = await generateNewsInsights(articles);
    setSummary(result);
    setLoading(false);
  };

  if (summary) {
    return (
      <div className="bg-blue-50 border border-blue-100 rounded-xl p-6 mb-10">
        <div className="flex justify-between items-start mb-4">
          <div className="flex items-center">
             <div className="p-1.5 bg-blue-100 rounded mr-3 text-primary-600">
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
             </div>
             <h2 className="text-lg font-bold text-slate-800">Smart Summary</h2>
          </div>
          <button 
            onClick={() => setSummary(null)}
            className="text-slate-400 hover:text-slate-600"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" /></svg>
          </button>
        </div>
        
        <div className="prose prose-sm max-w-none text-slate-700 leading-relaxed whitespace-pre-line">
           {summary}
        </div>
        <div className="mt-4 pt-3 border-t border-blue-100 text-xs text-slate-400 flex justify-end">
            Generated by Gemini 2.5 Flash
        </div>
      </div>
    );
  }

  return (
    <div className="mb-8 flex justify-end">
      <button
        onClick={handleGenerate}
        disabled={loading}
        className={`
          flex items-center px-4 py-2 rounded-lg text-sm font-medium transition-all
          ${loading 
            ? 'bg-slate-100 text-slate-400 cursor-not-allowed' 
            : 'bg-white text-slate-600 border border-slate-300 hover:border-primary-500 hover:text-primary-600'}
        `}
      >
        {loading ? (
          <>
            <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-primary-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            Generating...
          </>
        ) : (
          <>
            <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
               <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.384-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
            </svg>
            Get Summary
          </>
        )}
      </button>
    </div>
  );
};